site_name: enabel/partner-countries-bundle
site_description: Symfony partner countries management

repo_name: enabel/partner-countries-bundle
repo_url: https://github.com/Enabel/partner-countries-bundle
edit_uri: https://github.com/Enabel/partner-countries-bundle/edit/main/docs/

theme:
  name: readthedocs
  language: en

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/enabel/partner-countries-bundle
      name: enabel/partner-countries-bundle repository
  generator: false

plugins:
  - search: { }

nav:
  - Installation: 'index.md'
  - Command: 'command.md'
  - EasyAdmin: 'easyadmin.md'
  - Twig: 'twig.md'
  - 'Bug tracker': 'https://github.com/Enabel/partner-countries-bundle/issues'
